language: csharp
mono: none
dotnet: 5.0

before_script:
  - chmod +x ./build.sh

script:
  - ./build.sh

deploy:
  - provider: script
    script: dotnet nuget push DemoSdk.nupkg --api-key $MYGET_API_KEY --source https://www.myget.org/F/mydemosdk/api/v3/index.json
    skip_cleanup: true
    on:
      tags: true
